- mesatee_services/fns/sgx_trusted_lib/Cargo.toml
- mesatee_services/fns/sgx_trusted_lib/Enclave.config.xml
- toolchain_deps/Cargo.sgx_trusted_lib.toml
A bunch of updates/bug fixes in third party libraries.
Pin ring on version = 0.14.6 with tag = 0.14.6 in ring/sct.rs/webpki/rustls
> Upgrade dependencies. Pin ring on tag v0.14.6

- .bulldozer.yml
- .drone.yml
Revise CI and bulldozer config to make the PR process smooth:
- can utilizing our CI for building/testing
- our `mestee-mergebot` can work properly
> Update CI and bulldozer config to properly handle PR

- mesatee_services/tdfs/internal/client/src/tdfs_client.rs
Read/Write data with small buffer. 
Fixes #12 
Run PSI examples with large dataset.
Dataset: 100,000,000 data (about 1.5G) for each participant. 
FNS enclave configuration: 
```xml
<StackMaxSize>0x200000</StackMaxSize>
<HeapMaxSize>0x300000000</HeapMaxSize>
```
> Fix stack overflow and support large files

- mesatee_core/src/rpc/sgx/auth.rs
The ECDSA subject public key info parsing was buggy. This patch fixes the bug.
All integration tests depend on ECDSA parsing
> Fix a bug in parsing ECDSA public key

- docs/how_to_run.md
> docs: clarify spid and ias key configs

- CMakeLists.txt
- Makefile
- cmake/scripts/setup_cmake_tomls
- mesatee_cli/Cargo.toml
- mesatee_cli/src/main.rs
- toolchain_deps/Cargo.unix_app.toml
This PR adds a `curl`-like utlity tool that communicate with an external MesaTEE endpoint.
The help mesasge of this tool is like follows:
```shell
mesatee_cli 0.1.0
MesaTEE Authors <developers@mesatee.org>
MeasTEE client
USAGE:
mesatee_cli [FLAGS] [OPTIONS] <IP_ADDRESS:PORT> --auditor_keys <auditor_keys>... --auditor_sigs <auditor_sigs>... --enclave_info <enclave_info> --endpoint <endpoint>
FLAGS:
-h, --help
Prints help information
-P, --pretty
Enable pretty printing.
-V, --version
Prints version information
-v, --verbosity
Pass many times for more log output
By default, it'll only report errors. Passing `-v` one time also prints warnings, `-vv` enables info
logging, `-vvv` debug, and `-vvvv` trace.
OPTIONS:
-o, --output <IN_FILE>
Write to FILE instead of stdout
-i, --input <OUT_FILE> …
```
> utility: add mesatee_cli

- Makefile
Change Makefile to make enclave signatures more reproducible.
yes
> Change Makefile to make enclave signatures more reproducible.

- docs/how_to_build.md
Update SGX toolchain to 2.6.100 in docs.
N/A
> docs: update SGX toolchain to 2.6.100

- docs/api.md
- mesatee_services/kms/client/src/kms_client.rs
- mesatee_services/kms/proto/src/proto.rs
- mesatee_services/kms/sgx_trusted_lib/src/kms.rs
- mesatee_services/tdfs/external/client/src/tdfs_client.rs
- mesatee_services/tdfs/external/proto/src/proto.rs
- mesatee_services/tdfs/sgx_trusted_lib/src/data_store.rs
- mesatee_services/tdfs/sgx_trusted_lib/src/sgx.rs
- mesatee_services/tdfs/sgx_trusted_lib/src/tdfs_external.rs
- mesatee_services/tdfs/sgx_trusted_lib/src/tdfs_internal.rs
- mesatee_services/tms/external/client/src/tms_client.rs
- mesatee_services/tms/external/proto/src/proto.rs
- mesatee_services/tms/sgx_trusted_lib/src/data_store.rs
- mesatee_services/tms/sgx_trusted_lib/src/sgx.rs
- mesatee_services/tms/sgx_trusted_lib/src/tms_external.rs
- tests/functional_test/sgx_app/src/main.rs
- tests/functional_test/sgx_app/src/tests/common_setup.rs
- tests/functional_test/sgx_app/src/tests/fns_test.rs
- tests/functional_test/sgx_app/src/tests/tdfs_test.rs
- tests/functional_test/sgx_app/src/tests/tms_test.rs
- tests/functional_test/sgx_trusted_lib/src/sgx.rs
- tests/functional_test/sgx_trusted_lib/src/tests/kms_test.rs
This PR add three apis, including:
1) list tasks for the user
2) list files for the user
3) delete file (this involves another internal api: delete key in kms)
Fixes #34 
Functional tests for these apis are added.
> add apis to list task/file and delete file

- CMakeLists.txt
- Makefile
- examples/py_file/Cargo.toml
- examples/py_file/data/1.txt
- examples/py_file/payload.py
- examples/py_file/py_file.sh
- examples/py_file/py_result.txt
- examples/py_file/src/main.rs
- mesatee_services/fns/sgx_trusted_lib/src/global.rs
- mesatee_services/fns/sgx_trusted_lib/src/trusted_worker/mesapy.rs
- tests/integration_test.sh
- toolchain_deps/Cargo.unix_app.toml
Support file operation functions in the MesaPy worker. Usage can be seen in example payload: `examples/py_file/payload.py`.
Fixes #8
By the `py_file` project in examples.
> mesapy: support file operation functions in the python payload

- mesatee_services/fns/sgx_trusted_lib/src/fns.rs
Update task status if prepare_input function fails in FNS. 
Fixes #51
> fix prepare_input

- cmake/scripts/setup_cmake_tomls
1. Always setup cargo config for SGX to avoid outdated config.
2. Use blacklist so there is no need to modify this file when adding new
directory under project root.
> Improve setup_cmake_tomls

- docs/how_to_build.md
Add more details for how to build.
> Add more details for how to build.

- DISCLAIMER
Add the DISCLAIMER file in the repo according to the incubator policy: https://incubator.apache.org/policy/incubation.html
> Add the DISCLAIMER file

- cmake/scripts/parse_cargo_packages.py
- cmake/scripts/setup_cmake_tomls
Improve code style of python scripts used by CMake.
Yes
> Improve code style of python scripts used by CMake.

- mesatee_services/fns/sgx_trusted_lib/Cargo.toml
As discussed in the mailing list, we need prost to improve RPC mechanism. With the help of prost, we do not need handcrafted `.rs` file for each proto. Instead, we can simply maintain the `.proto` file and use `prost` to generate the corresponding Rust source codes.
Accompanied with update on regular third party crates.
CI succeed. [proof](http://ci.mesalock-linux.org/dingelish/incubator-mesatee/2/1/5).
> Add prost, and update third party crates.

- .drone.yml
- Dockerfile
Since ACS needs pypy/pypy-dev, we need to update the Dockerfile and DockerHub accordingly.
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/3
> Add pypy/pypy-dev as build dependencies in Dockerfile

- CMakeLists.txt
- examples/py_file/data/1.txt
- examples/py_file/payload.py
- mesatee_services/fns/sgx_trusted_lib/src/global.rs
This commit update mesapy and fix FFI calling convention. The MesaPy fix can be found here: https://github.com/mesalock-linux/mesapy/commit/2b7ea38773d337d106c613a239661a60a4fa7528
Fixes #63 (issue)
CI result can be seen here: https://ci.mesalock-linux.org/mssun/incubator-mesatee/1
The `py_file` example.
> Update mesapy to fix FNS/MesaPy FFI issues

- .drone.yml
Separate clippy to another pipeline. This will reduce building time from 14m to 11m.
CI
> CI: separate clippy to another pipeline

- CMakeLists.txt
Add more dependency check, including (lsof, pypy and pypy-dev).
Yes
> Add more dependency check

- .gitmodules
Ignore dirty changes for the `third-party/crates-sgx` submodule.
- clean up
CI
> Ignore dirty changes for third-party/crates-sgxsubmodule

- CMakeLists.txt
- cmake/scripts/prep.sh
Automatically download new mesapy if the version was changed.
Yes
> Automatically download new mesapy if the version was changed.

- .drone.yml
Refactor drone.yml:
- add coverage pipeline
- add doc pipeline
- rename pipelines
coverage and doc pipeline will be trigger when push to the master branch. I installed a pull bot (https://github.com/wei/pull) in my own fork (https://github.com/mssun/incubator-mesatee) to automatically merge the upstream update. This will trigger doc and coverage pipeline. By this way, we can still use drone and work as usually.
- CI refactor
CI (but doc and coverage will be trigger when pull bot trigger a push commit to my master)
> Refactor drone.yml

- .gitmodules
- cmake/scripts/setup_cmake_tomls
Vendor all Rust libraries from crates.io.
Fixes #66
- building system
See CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/51
> Vendor all Rust libraries from crates-io

- .gitignore
Ignore release directory, which contains all released bin, services, examples, etc.
N/A
> Ignore release directory

- CMakeLists.txt
- cmake/MesaTEEGenVars.cmake
- cmake/MesaTEEUtils.cmake
- cmake/tomls/Cargo.sgx_trusted_lib.toml
- examples/gbdt/Cargo.toml
- mesatee_services/fns/sgx_trusted_lib/Cargo.toml
Ensure all crates usage are from third-party vendor directory. No more "updating" when building multiple times.
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/57
> Ensure all crates usages are from vendor dir

- CMakeLists.txt
- cmake/MesaTEEUtils.cmake
- cmake/scripts/sgx_link_sign.sh
- tests/functional_test.sh
- tests/integration_test.sh
Sort enclave.signed.so files into different folders according to their src paths.
This is not a bug by the way.
Fixes #114 
Yes
> Sort enclave.signed.so files into different folders

- mesatee_services/kms/proto/build.rs
Only generate rust files for proto files if proto files are changed. 
Fixes #123 
Passed CI.  
Compiled the project multiple times in local. 
http://ci.mesalock-linux.org/litongxin1991/incubator-mesatee/35
> cache for build.rs

- docker/README.md
> [docker] Add README.md for docker

- docker/docker-compose-ubuntu-1604.yml
- docker/docker-compose-ubuntu-1804.yml
Add env var ( MESATEE_CFG_DIR=. in docker-compose) to avoid the "Missing environment variable MESATEE_CFG_DIR. Using "."" warning.
Self-tested.
- [x Fork the repo and create your branch from `master`.
> [docker] Add env var MESATEE_CFG_DIR=. in docker-compose

- docker/README.md
- docker/docker-compose-ubuntu-1604.yml
- docker/docker-compose-ubuntu-1804.yml
Update README.md and set RUST_LOG default value.
Self-tested.
> [docker] Update README.md and set RUST_LOG default value

- cmake/MesaTEEGenVars.cmake
- cmake/MesaTEEUtils.cmake
- cmake/UtilTargets.cmake
- Remove clippy-xxx targets since make CLP=1 xxx is good enough, (make clippy is kept for convenience).
- Remove unused util variables and functions for clippy-xxx targets.
Yes
> Clean clippy related utils

- docker/docker-compose-ubuntu-1604.yml
- docker/docker-compose-ubuntu-1804.yml
- docker/fns-rt.ubuntu-1604.Dockerfile
- docker/fns-rt.ubuntu-1804.Dockerfile
- docker/kms-rt.ubuntu-1604.Dockerfile
- docker/kms-rt.ubuntu-1804.Dockerfile
- docker/runtime.config.toml
- docker/tdfs-rt.ubuntu-1604.Dockerfile
- docker/tdfs-rt.ubuntu-1804.Dockerfile
- docker/tms-rt.ubuntu-1604.Dockerfile
- docker/tms-rt.ubuntu-1804.Dockerfile
Use updated `runtime.config.toml` for docker-compose file.
Self-tested. This has not been integrated into CI procedure yet.
> [docker] Use the updated runtime.config.toml

- .drone.yml
Don't mount SGX device for simulation mode
> [ci] Don't mount SGX device for simulation mode

- DISCLAIMER
- NOTICE
Update DISCLAIMER and add NOTICE in the Apache way [1, 2].
1. https://incubator.apache.org/guides/branding.html#disclaimers
2. http://www.apache.org/dev/licensing-howto.html
> Rename to Apache Teaclave (incubating) and add NOTICE file

- mesatee_core/Cargo.toml
- mesatee_core/src/config/external.rs
- mesatee_core/src/config/internal.rs
- mesatee_core/src/lib.rs
- mesatee_core/src/rpc/sgx/mod.rs
- mesatee_core/src/rpc/sgx/ra.rs
- mesatee_services/acs/sgx_app/build.rs
- mesatee_services/acs/sgx_trusted_lib/Cargo.toml
- mesatee_services/acs/sgx_trusted_lib/src/sgx.rs
- mesatee_services/fns/sgx_app/build.rs
- mesatee_services/fns/sgx_trusted_lib/Cargo.toml
- mesatee_services/fns/sgx_trusted_lib/src/sgx/mod.rs
- mesatee_services/kms/sgx_app/build.rs
- mesatee_services/kms/sgx_app/src/main.rs
- mesatee_services/kms/sgx_trusted_lib/Cargo.toml
- mesatee_services/kms/sgx_trusted_lib/src/sgx.rs
- mesatee_services/tdfs/sgx_app/build.rs
- mesatee_services/tdfs/sgx_app/src/main.rs
- mesatee_services/tdfs/sgx_trusted_lib/Cargo.toml
- mesatee_services/tdfs/sgx_trusted_lib/src/sgx.rs
- mesatee_services/tms/sgx_trusted_lib/Cargo.toml
- mesatee_services/tms/sgx_trusted_lib/src/sgx.rs
- teaclave_config/Cargo.toml
- teaclave_config/src/lib.rs
- tests/functional_test/sgx_app/build.rs
- tests/functional_test/sgx_trusted_lib/src/sgx.rs
Make runtime config optional and handle none config at enclave init
Fixes #161
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/165
> [config] Make runtime config optional and handle none config at enclave init

- mesatee_core/src/lib.rs
Fix compilation issue introduce by 4220e33
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/175
> Fix compilation issue

- mesatee_core/src/error.rs
- mesatee_core/src/rpc/mod.rs
Handle RPC invoke error.
Fix #85
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/68
> Handle RPC invoke error

- docs/how_to_run.md
> update how_to_build.md about export values

- mesatee_core/src/config/external.rs
- mesatee_core/src/config/internal.rs
- mesatee_core/src/config/mod.rs
- mesatee_core/src/lib.rs
- mesatee_core/src/rpc/sgx/mod.rs
- mesatee_core/src/rpc/sgx/ra.rs
- teaclave_config/src/lib.rs
Reorganize `mesate_core/config` and `teaclave_config`.
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/191
> Reorganize mesate_core/config and teaclave_config

- examples/quickstart/Cargo.toml
- examples/quickstart/src/main.rs
Two sub-commands:
echo:
```
./release/examples/quickstart echo -e release/examples/enclave_info.toml -i "Hello, World!"
```
psi:
```
MESATEE_STORAGE_DIR=/tmp/mesatee_storage ./release/examples/quickstart psi -e release/examples/enclave_info.toml -f tests/integration_test/test_data/psi1.txt  -f tests/integration_test/test_data/psi2.txt
```
Note that this PR is to have a better interfaces. I'll come back to polish the code. Thanks.
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/216
> Rewrite quickstart example command line interface

- mesatee_core/src/rpc/sgx/ra.rs
Refactor ECC key and cert generation functions to make them more readable.
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/253
> [core] Refactor ECC key conversion and cert generation functions

- attestation/src/cert.rs
- attestation/src/report.rs
Get rid of some lifetime parameters so that we can avoid some clippy warnings
> Remove unnecessary lifetime arguments in cert parsing code

- cmake/scripts/prep.sh
- tests/functional_tests/enclave/src/teaclave_execution_service.rs
- tests/integration_tests/enclave/src/teaclave_worker.rs
- tests/unit_tests/enclave/Cargo.toml
- tests/unit_tests/enclave/src/lib.rs
- types/Cargo.toml
- types/src/crypto.rs
- types/src/lib.rs
- types/src/unittest.rs
- types/src/worker.rs
- worker/src/function/gbdt_training.rs
- worker/src/lib.rs
- worker/src/runtime/default.rs
- worker/src/runtime/mod.rs
- worker/src/runtime/raw_io.rs
> [worker] Support encrypted/raw input with tests.

- tests/functional_tests/enclave/src/teaclave_execution_service.rs
- tests/integration_tests/enclave/src/teaclave_worker.rs
- types/src/worker.rs
- worker/src/runtime/default.rs
> [worker] Support encrypted output with test.

- tests/functional_tests/enclave/src/lib.rs
- tests/integration_tests/enclave/src/lib.rs
- tests/test_utils/src/lib.rs
- tests/unit_tests/enclave/Cargo.toml
- tests/unit_tests/enclave/src/lib.rs
- worker/src/lib.rs
> [tests] Introduce check_all_passed macro

- tests/test_cases/mesapy/input.txt
- types/src/worker.rs
- worker/Cargo.toml
- worker/src/function/context.rs
- worker/src/function/gbdt_training.rs
- worker/src/function/mesapy.rs
- worker/src/function/mod.rs
- worker/src/lib.rs
> [workers] Bridging mesapy with tests

- CMakeLists.txt
- cmake/scripts/sgx_link_sign.sh
- cmake/scripts/test.sh
- cmake/tomls/Cargo.sgx_trusted_lib.toml
- cmake/tomls/Cargo.sgx_untrusted_app.toml
- config/runtime.config.toml
- config/src/runtime.rs
- services/access_control/app/Cargo.toml
- services/access_control/app/build.rs
- services/access_control/app/src/main.rs
- services/access_control/enclave/Cargo.toml
- services/access_control/enclave/Enclave.config.xml
- services/access_control/enclave/src/acs.rs
- services/access_control/enclave/src/lib.rs
- services/access_control/enclave/src/service.rs
- services/access_control/model.conf
- services/access_control/python/acs_engine.py
- services/access_control/python/acs_engine_test.py
- services/access_control/python/ffi.py
- services/proto/build.rs
- services/proto/src/lib.rs
- services/proto/src/proto/teaclave_access_control_service.proto
- services/proto/src/teaclave_access_control_service.rs
- tests/fixtures/runtime.config.toml
- tests/functional_tests/enclave/src/lib.rs
- tests/functional_tests/enclave/src/teaclave_access_control_service.rs
- tests/unit_tests/enclave/Cargo.toml
- tests/unit_tests/enclave/src/lib.rs
Implement access control service
> add access control service

- services/proto/src/teaclave_common.rs
- services/proto/src/teaclave_execution_service.rs
- tests/functional_tests/enclave/src/teaclave_execution_service.rs
- tests/integration_tests/enclave/src/teaclave_worker.rs
- types/Cargo.toml
- types/src/crypto.rs
- types/src/worker.rs
- worker/src/function/context.rs
- worker/src/function/gbdt_training.rs
- worker/src/function/mesapy.rs
> [types] Remove ser/de for worker structs with polished tests

- cmake/scripts/test.sh
- config/runtime.config.toml
- services/management/enclave/Cargo.toml
- services/management/enclave/src/file.rs
- services/management/enclave/src/lib.rs
- services/management/enclave/src/service.rs
- tests/fixtures/runtime.config.toml
- tests/functional_tests/enclave/src/lib.rs
- tests/functional_tests/enclave/src/teaclave_management_service.rs
- tests/unit_tests/enclave/Cargo.toml
- tests/unit_tests/enclave/src/lib.rs
- types/src/crypto.rs
Implement register_input_file and register_output_file in management service. 
> implement some requests in management service

- services/management/enclave/src/file.rs
- services/management/enclave/src/fusion_data.rs
- services/management/enclave/src/lib.rs
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/proto/teaclave_management_service.proto
- services/proto/src/teaclave_frontend_service.rs
- tests/functional_tests/enclave/src/teaclave_management_service.rs
implement more requests in management service
> implement more requests in management service

- services/management/enclave/src/function.rs
- services/management/enclave/src/lib.rs
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/proto/teaclave_management_service.proto
- services/proto/src/teaclave_frontend_service.rs
- tests/functional_tests/enclave/src/teaclave_management_service.rs
Handle function in management service
> handle function in management service

- CMakeLists.txt
- worker/src/function/context.rs
- worker/src/function/mesapy.rs
> [worker] mesapy ffi and io with tests

- common/protected_fs_rs/src/sgx_tprotected_fs.rs
- tests/integration/enclave/src/rusty_leveldb_sgx.rs
> [common] Fix read/write buffer check with leveldb test case

- services/frontend/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/teaclave_frontend_service.rs
- tests/functional/enclave/src/teaclave_frontend_service.rs
> implement frontend service

- cmake/scripts/test.sh
- services/management/enclave/src/lib.rs
- services/management/enclave/src/service.rs
- services/management/enclave/src/task.rs
- tests/functional/enclave/src/teaclave_management_service.rs
- types/Cargo.toml
- types/src/file.rs
- types/src/lib.rs
> [types, services] Move in/out file structure to types

- .drone.yml
- services/proto/src/proto/teaclave_execution_service.proto
- services/proto/src/teaclave_common.rs
- services/proto/src/teaclave_execution_service.rs
- tests/functional/enclave/src/teaclave_execution_service.rs
- tests/integration/enclave/src/teaclave_worker.rs
- types/src/worker.rs
- worker/src/function/context.rs
- worker/src/function/gbdt_prediction.rs
- worker/src/function/gbdt_training.rs
- worker/src/function/mesapy.rs
- worker/src/runtime/default.rs
- worker/src/runtime/raw_io.rs
- worker/src/worker.rs
> [types] Split TeaclveWorkerFile into Input and Output.

- cmake/scripts/test.sh
- cmake/tomls/Cargo.sgx_trusted_lib.toml
- cmake/tomls/Cargo.sgx_untrusted_app.toml
- config/build.config.toml
- config/config_gen/main.rs
- config/config_gen/templates/config.j2
- config/runtime.config.toml
- config/src/runtime.rs
- services/proto/build.rs
- services/proto/src/lib.rs
- services/proto/src/proto/teaclave_scheduler_service.proto
- services/proto/src/teaclave_scheduler_service.rs
- services/scheduler/app/Cargo.toml
- services/scheduler/app/build.rs
- services/scheduler/app/src/main.rs
- services/scheduler/enclave/Cargo.toml
- services/scheduler/enclave/Enclave.config.xml
- services/scheduler/enclave/src/lib.rs
- services/scheduler/enclave/src/service.rs
- tests/fixtures/runtime.config.toml
- tests/integration/app/src/teaclave_config_tests.rs
- tests/unit/enclave/Cargo.toml
> partially implement scheduler service

- cmake/TeaclaveUtils.cmake
- services/management/enclave/src/service.rs
> [build] Fix non TEST_MODE make issue

- README.md
Update README to add links to the develop branch for the latest implementation.
Since we have branch protection on the `master` branch, this PR needs at least one reviewer to approve.
> [readme] Point to the develop branch for the latest implementation

- cmake/scripts/test.sh
- file_agent/Cargo.toml
- file_agent/src/agent.rs
- file_agent/src/lib.rs
- tests/scripts/simple_http_server.py
- types/src/worker.rs
> [agent] Introduce file agent

- file_agent/src/agent.rs
> [agent] Add more tests for file agent

- services/execution/enclave/src/lib.rs
- services/execution/enclave/src/service.rs
- types/src/worker.rs
- worker/src/function/echo.rs
- worker/src/worker.rs
> [worker] Add Echo function.

- common/rusty_leveldb_sgx/Cargo.toml
- common/rusty_leveldb_sgx/src/disk_env.rs
- common/rusty_leveldb_sgx/src/env.rs
- common/rusty_leveldb_sgx/src/lib.rs
- common/rusty_leveldb_sgx/src/mem_env.rs
- common/rusty_leveldb_sgx/src/options.rs
- tests/unit/enclave/Cargo.toml
- tests/unit/enclave/src/lib.rs
> [common] Make leveldb sgx only and enable unit test.

- common/rusty_leveldb_sgx/src/block.rs
- common/rusty_leveldb_sgx/src/block_builder.rs
- common/rusty_leveldb_sgx/src/blockhandle.rs
- common/rusty_leveldb_sgx/src/cache.rs
- common/rusty_leveldb_sgx/src/cmp.rs
- common/rusty_leveldb_sgx/src/db_impl.rs
- common/rusty_leveldb_sgx/src/db_iter.rs
- common/rusty_leveldb_sgx/src/filter.rs
- common/rusty_leveldb_sgx/src/filter_block.rs
- common/rusty_leveldb_sgx/src/key_types.rs
- common/rusty_leveldb_sgx/src/lib.rs
- common/rusty_leveldb_sgx/src/log.rs
- common/rusty_leveldb_sgx/src/mem_env.rs
- common/rusty_leveldb_sgx/src/memtable.rs
- common/rusty_leveldb_sgx/src/merging_iter.rs
- common/rusty_leveldb_sgx/src/skipmap.rs
- common/rusty_leveldb_sgx/src/snapshot.rs
- common/rusty_leveldb_sgx/src/table_builder.rs
- common/rusty_leveldb_sgx/src/table_cache.rs
- common/rusty_leveldb_sgx/src/table_reader.rs
- common/rusty_leveldb_sgx/src/test_util.rs
- common/rusty_leveldb_sgx/src/types.rs
- common/rusty_leveldb_sgx/src/version.rs
- common/rusty_leveldb_sgx/src/version_edit.rs
- common/rusty_leveldb_sgx/src/version_set.rs
- common/rusty_leveldb_sgx/src/write_batch.rs
- tests/unit/enclave/Enclave.config.xml
- tests/utils/src/lib.rs
> [common] Enable all unit_test for rusty_leveldb_sgx

- services/execution/enclave/src/service.rs
- tests/integration/enclave/src/teaclave_worker.rs
- types/src/staged_file.rs
- types/src/staged_function.rs
- worker/src/function/context.rs
- worker/src/function/gbdt_prediction.rs
- worker/src/function/gbdt_training.rs
- worker/src/function/mesapy.rs
- worker/src/runtime/default.rs
- worker/src/runtime/raw_io.rs
- worker/src/worker.rs
> [types] Simplify StagedFiles related structures

- function/src/context.rs
- function/src/gbdt_prediction.rs
- function/src/gbdt_training.rs
- function/src/mesapy.rs
- runtime/src/default.rs
- runtime/src/raw_io.rs
- types/src/macros.rs
- types/src/staged_file.rs
> [types] Optimize StagedFiles usages

- cmake/scripts/test.sh
- services/execution/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/teaclave_frontend_service.rs
- tests/functional/enclave/src/end_to_end.rs
- tests/functional/enclave/src/lib.rs
- types/src/task.rs
> [tests] Add End-to-End echo function test.

- tests/functional/enclave/Cargo.toml
- tests/functional/enclave/src/end_to_end.rs
> [tests] End-to-End test with helper functions

- .drone.yml
- dcap/src/main.rs
- docker/build.ubuntu-1804.sgx-dcap-1.5.Dockerfile
Introduce Dockerfile to build Teaclave with SGX DCAP 1.5, and re-enable the temporarily disabled DCAP CI pipeline.
CI passed: https://ci.mesalock-linux.org/mssun/incubator-mesatee/631
> [dcap] Enable SGX DCAP 1.5

- common/rusty_leveldb_sgx/src/version_set.rs
- services/execution/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/src/teaclave_frontend_service.rs
- tests/functional/enclave/src/end_to_end/mesapy_echo.rs
- tests/functional/enclave/src/end_to_end/native_echo.rs
- tests/functional/enclave/src/execution_service.rs
- tests/functional/enclave/src/frontend_service.rs
- tests/functional/enclave/src/management_service.rs
- tests/functional/enclave/src/scheduler_service.rs
- tests/integration/enclave/src/teaclave_worker.rs
- types/src/staged_function.rs
- types/src/staged_task.rs
- types/src/task.rs
- types/src/worker.rs
- worker/src/worker.rs
> [executor] Use Executor to replace native function String.

- services/access_control/enclave/src/service.rs
- services/proto/src/teaclave_frontend_service.rs
- tests/functional/enclave/src/end_to_end/mesapy_echo.rs
- tests/functional/enclave/src/end_to_end/mod.rs
- tests/functional/enclave/src/end_to_end/native_echo.rs
- tests/functional/enclave/src/frontend_service.rs
- tests/functional/enclave/src/management_service.rs
- tests/functional/enclave/src/utils.rs
> [tests] Unify functional tests requests logic.

- services/execution/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/proto_gen/templates/proto.j2
- services/proto/src/proto/teaclave_common.proto
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/proto/teaclave_scheduler_service.proto
- services/proto/src/teaclave_common.rs
- services/proto/src/teaclave_frontend_service.rs
- services/proto/src/teaclave_scheduler_service.rs
- services/scheduler/enclave/src/service.rs
- tests/functional/enclave/src/end_to_end/mesapy_echo.rs
- tests/functional/enclave/src/end_to_end/mod.rs
- tests/functional/enclave/src/end_to_end/native_echo.rs
- tests/functional/enclave/src/end_to_end/native_gbdt_training.rs
- tests/functional/enclave/src/execution_service.rs
- types/src/task.rs
> [task] Unify task result field with TaskResult

- cmake/scripts/test.sh
- common/protected_fs_rs/src/protected_fs.rs
- common/protected_fs_rs/tests/large_file.rs
- common/protected_fs_rs/tests/rename.rs
- services/execution/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/teaclave_frontend_service.rs
- tests/functional/enclave/src/end_to_end/native_gbdt_training.rs
- tests/functional/enclave/src/frontend_service.rs
- tests/functional/enclave/src/management_service.rs
- types/src/crypto.rs
- types/src/file.rs
- types/src/staged_task.rs
> [types] Add FileAuthTag type.

- README.md
Remove outdated content in README.md and polish the description.
More content will be added later.
> Remove outdated content in README.md and polish the description

- runtime/src/default.rs
- runtime/src/raw_io.rs
- services/execution/enclave/src/service.rs
- services/execution/enclave/src/task_file_manager.rs
- services/proto/src/teaclave_common.rs
- types/src/staged_file.rs
- types/src/staged_task.rs
- types/src/task.rs
- types/src/worker.rs
> [cmac] Add output cmac.

- attestation/Cargo.toml
- attestation/src/attestation.rs
- attestation/src/cert.rs
- attestation/src/key.rs
- attestation/src/lib.rs
- attestation/src/platform.rs
- attestation/src/report.rs
- attestation/src/service.rs
- attestation/src/verifier.rs
- services/access_control/enclave/src/lib.rs
- services/authentication/enclave/src/lib.rs
- services/frontend/enclave/src/lib.rs
- services/management/enclave/src/lib.rs
- services/scheduler/enclave/src/lib.rs
- services/storage/enclave/src/lib.rs
This PR includes more docs, comments, as well as some API polishing.
> [attestation] Improve documentation and API polishing

- cmake/scripts/test.sh
- config/runtime.config.toml
- config/src/runtime.rs
- crypto/Cargo.toml
- crypto/src/lib.rs
- services/execution/enclave/src/lib.rs
- services/execution/enclave/src/service.rs
- services/management/enclave/src/lib.rs
- services/management/enclave/src/service.rs
- tests/fixtures/fusion/input1.txt
- tests/fixtures/fusion/input2.txt
- tests/functional/enclave/src/end_to_end/mesapy_data_fusion.rs
- tests/functional/enclave/src/end_to_end/mesapy_echo.rs
- tests/functional/enclave/src/end_to_end/mod.rs
- tests/functional/enclave/src/end_to_end/native_echo.rs
- tests/functional/enclave/src/end_to_end/native_gbdt_training.rs
- tests/functional/enclave/src/frontend_service.rs
- tests/functional/enclave/src/utils.rs
- types/src/file.rs
> [fusion] Support fusion data creation with example.

- README.md
- docs/README.md
- docs/rust-guideline.md
- docs/threat-model.md
- tests/README.md
- Update our threat model
- Add Rust development guideline
> [docs] Update docs and add rust guideline

- services/execution/enclave/src/service.rs
- services/execution/enclave/src/task_file_manager.rs
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_common.proto
- services/proto/src/teaclave_common.rs
- services/scheduler/enclave/Cargo.toml
- services/scheduler/enclave/src/service.rs
- tests/functional/enclave/src/end_to_end/mesapy_data_fusion.rs
- tests/functional/enclave/src/end_to_end/mesapy_echo.rs
- tests/functional/enclave/src/end_to_end/mod.rs
- tests/functional/enclave/src/end_to_end/native_echo.rs
- tests/functional/enclave/src/end_to_end/native_gbdt_training.rs
- tests/functional/enclave/src/scheduler_service.rs
- types/src/file.rs
- types/src/staged_task.rs
- types/src/task.rs
- types/src/worker.rs
> [fusion] Support fusion data used as input with example.

- CONTRIBUTORS.md
- cli/README.md
- cli/src/main.rs
- config/README.md
- Update `CONTRIBUTORS.md`
- Add document for `cli` and `config`
> Add and update documents

- config/README.md
- dcap/README.md
- docs/mutual-attestation.md
- docs/my-first-function.md
- docs/threat-model.md
- Add DCAP readme
- Fix some minor issues in other docs
> [dcap] Add README.md

- services/execution/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_common.proto
- services/proto/src/proto/teaclave_scheduler_service.proto
- services/proto/src/teaclave_common.rs
- services/proto/src/teaclave_scheduler_service.rs
- services/scheduler/enclave/src/service.rs
- tests/functional/enclave/src/end_to_end/native_echo.rs
- tests/functional/enclave/src/execution_service.rs
- tests/functional/enclave/src/frontend_service.rs
- tests/functional/enclave/src/management_service.rs
- tests/functional/enclave/src/scheduler_service.rs
- types/src/staged_function.rs
- types/src/task.rs
> [task] Restrict task status transition.

- .drone.yml
- executor/Cargo.toml
- executor/src/builtin.rs
- executor/src/context.rs
- executor/src/lib.rs
- executor/src/mesapy.rs
- function/src/echo.rs
- function/src/gbdt_predict.rs
- function/src/gbdt_train.rs
- function/src/logistic_regression_predict.rs
- function/src/logistic_regression_train.rs
- services/execution/enclave/src/lib.rs
- services/execution/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/src/teaclave_frontend_service.rs
- tests/functional/enclave/src/end_to_end/builtin_echo.rs
- tests/functional/enclave/src/end_to_end/builtin_gbdt_train.rs
- tests/functional/enclave/src/end_to_end/mod.rs
- tests/functional/enclave/src/execution_service.rs
- tests/functional/enclave/src/scheduler_service.rs
- tests/integration/enclave/src/teaclave_worker.rs
- tests/unit/enclave/Cargo.toml
- tests/unit/enclave/src/lib.rs
- types/src/staged_function.rs
- types/src/staged_task.rs
- types/src/task.rs
- types/src/worker.rs
- worker/Cargo.toml
- worker/src/worker.rs
- worker: defines runtime and executor
- runtime: interfaces with the platform (e.g., IO) in functions
- executor: function executor, we only have two executors: 1) mesapy, 2) builtin function executor
- function: defines all platform builtin functions
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/735
> Reorganize worker, runtime, executor, and function

- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/teaclave_frontend_service.rs
- services/scheduler/enclave/src/service.rs
- tests/functional/enclave/src/end_to_end/builtin_gbdt_train.rs
- tests/functional/enclave/src/end_to_end/mesapy_data_fusion.rs
- tests/functional/enclave/src/frontend_service.rs
- tests/functional/enclave/src/management_service.rs
- types/src/file.rs
- types/src/staged_task.rs
- types/src/task.rs
> [task] Wrap types for Task fields.

- README.md
- config/build.config.toml
- docs/my-first-function.md
- services/README.md
- Add `README.md` to the `services` directory
- Add a "Codebase" subsection in the root `README.md` pointing to different directories
> [services] Add README.md

- .drone.yml
- CMakeLists.txt
- docs/my-first-function.md
- Check Intel SGX SDK version in cmake
- Add instructions to setting up attestation service (IAS)
> Improve building system and instructions to setting up attesation service

- config/src/runtime.rs
- services/access_control/enclave/src/lib.rs
- services/authentication/enclave/src/lib.rs
- services/execution/enclave/src/lib.rs
- services/frontend/enclave/src/lib.rs
- services/management/enclave/src/lib.rs
- services/scheduler/enclave/src/lib.rs
- services/storage/enclave/src/lib.rs
- tests/functional/enclave/src/authentication_service.rs
- tests/functional/enclave/src/utils.rs
- Cleanup unwraps when launching the services
- Log errors when failing to start the services
CI passed: https://ci.mesalock-linux.org/mssun/incubator-mesatee/752
> [services] Cleanup unwrap and provide better error handling

- docker/teaclave-rt.ubuntu-1804.Dockerfile
Fixes #287 in the runtime docker.
> [docker] Make fusion data directory in runtime docker file

- config/src/lib.rs
- config/src/runtime.rs
- services/access_control/app/Cargo.toml
- services/access_control/app/src/main.rs
- services/authentication/app/Cargo.toml
- services/authentication/app/src/main.rs
- services/execution/app/Cargo.toml
- services/execution/app/src/main.rs
- services/frontend/app/Cargo.toml
- services/frontend/app/src/main.rs
- services/management/app/Cargo.toml
- services/management/app/src/main.rs
- services/scheduler/app/Cargo.toml
- services/scheduler/app/src/main.rs
- services/storage/app/Cargo.toml
- services/storage/app/src/main.rs
- services/utils/service_app_utils/Cargo.toml
- services/utils/service_app_utils/src/lib.rs
- Introduce `TeaclaveServiceLauncher` to simplify app part of services
CI Passed: https://ci.mesalock-linux.org/mssun/incubator-mesatee/757
> [services] Introduce TeaclaveServiceLauncher to simplify app part of services

- docs/my-first-function.md
- Add instructions to build/run in simulation mode
> [docs] Add instructions to build/run in simulaiton mode

- file_agent/src/agent.rs
- services/execution/enclave/src/lib.rs
- services/execution/enclave/src/ocall.rs
- services/execution/enclave/src/service.rs
- services/execution/enclave/src/task_file_manager.rs
- services/management/enclave/src/lib.rs
- services/management/enclave/src/service.rs
- types/src/file_agent.rs
FusionBase directory is a runtime configuration item for Execution Service. The absolute path of a fusion file is resolved outside of enclave, combining the fusion_base_dir and relative path assigned by Management service.
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/237
> [fusion] Optimize fusion_base dir logic.

- cmake/UtilTargets.cmake
- cmake/scripts/test.sh
- examples/python/builtin_echo.py
- tests/scripts/simple_http_server.py
- implement an example written in Python (builtin echo)
CI passed: https://ci.mesalock-linux.org/mssun/incubator-mesatee/766
> Implement an example in Python (builtin echo)

- services/management/enclave/src/service.rs
- services/scheduler/enclave/src/service.rs
- tests/functional/enclave/src/end_to_end/builtin_echo.rs
- tests/functional/enclave/src/execution_service.rs
- tests/functional/enclave/src/scheduler_service.rs
- types/src/lib.rs
- types/src/task.rs
- types/src/task_state.rs
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/243/5/5]
> [task] Bind Task state to static type.

- README.md
- docs/my-first-function.md
- Include the echo function example in the doc
> [docs] Include the echo function example in doc

- cli/README.md
- config/README.md
- dcap/README.md
- docker/README.md
- docs/README.md
- docs/mutual-attestation.md
- docs/my-first-function.md
- docs/rust-guideline.md
- docs/threat-model.md
- keys/README.md
- services/README.md
- Declare permalink in docs for website
> [docs] Declare permalink in docs for website

- COMMUNITY.md
- CONTRIBUTORS.md
- Add COMMUNITY.md to provide community information, this will be presented in our homepage.
> Add COMMUNITY.md to provide community information

- docs/my-first-function.md
- Fix docker image and command for building in the get started documentation
> [docs] Fix docker image and command for building

- docs/my-first-function.md
> [docs] Add instruction to change the docker-compose file for the simulation mode

- cmake/scripts/test.sh
- docs/my-first-function.md
- examples/python/builtin_echo.py
- examples/python/mesapy_echo.py
- sdk/python/teaclave.py
- Add the mesapy echo example.
- Move some functions to SDK
> [examples, sdk] Add the mesapy_echo example and move some functions into Python SDK

- examples/python/builtin_echo.py
- examples/python/mesapy_echo.py
- examples/python/utils.py
- sdk/python/teaclave.py
- Improve the Python SDK and update examples
CI pass: https://ci.mesalock-linux.org/mssun/incubator-mesatee/792
> [sdk] Improve the Python SDK and update examples

- types/src/task_state.rs
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/254
> [task] Remove task clone before saving state into db.

- docs/my-first-function.md
Update instructions for simulation mode. Fix #305
> [docs] Set SGX_MODE=SW in simulation mode

- README.md
- executor/Cargo.toml
- executor/README.md
- executor/src/builtin.rs
- worker/Cargo.toml
- Add `README.md` for executor
- Put built-in functions in features
> [docs] Add README.md for executor

- COMMUNITY.md
- executor/README.md
- Update community information and add organizations and projects using Teaclave
> More community information

- README.md
- worker/README.md
> Add docs for worker

- CONTRIBUTORS.md
- README.md
- config/README.md
- executor/README.md
- function/README.md
- services/README.md
- tests/README.md
- third_party/README.md
- Polish and improve documentation
- Add document for built-in functions
> Polish and improve documentation

- config/README.md
- docs/README.md
- docs/my-first-function.md
- examples/python/mesapy_echo.py
- examples/python/mesapy_echo_payload.py
- Add "define my own function" section into "my first function" doc.
- Improve other docs.
>  Add document on defining customized function

- cmake/scripts/test.sh
- examples/python/builtin_gbdt_train.py
- sdk/python/teaclave.py
Add builtin_gbdt_train python script to help people use python sdk. All my codes have been tested. But I **do not** add them into teaclave tests, because I dont know how to do that... So could u guys help me finish the final shot? BTW, builtin_gbdt_predict python script and codes about LR thing are on the way.
> add builtin_gbdt_train python script

- README.md
- docs/build-system.md
- tests/README.md
- Add doc for the build system
Fix #93
> [docs] Add doc for the build system

- README.md
- attestation/README.md
> [docs] Add doc for Attestation

- attestation/README.md
- Put title in the first line so that the website can extract it.
> [docs] Fix title position

- docs/mutual-attestation.md
> [docs] Fix typo

- README.md
- docs/README.md
- rpc/README.md
- Add doc for the RPC framework
> [docs] Add doc for the RPC framework

- COMMUNITY.md
- Add the Secret Network blockchain to the community
> Add the Secret Network blockchain to the community

- common/protected_fs_rs/protected_fs_c/sgx_tprotected_fs/file_other.cpp
protected_fs::rename_meta and get_current_meta_gmac missing mutex synchronization protection.
> fix protected_fs::rename_meta and get_current_meta_gmac: add mutex sync

- .drone.yml
- cmake/UtilTargets.cmake
- cmake/scripts/test.sh
- services/execution/enclave/src/lib.rs
- services/frontend/enclave/src/lib.rs
- services/management/enclave/src/lib.rs
- services/scheduler/enclave/src/lib.rs
- services/utils/service_enclave_utils/src/lib.rs
- Enable mutual attestation in `create_trusted_*_endpoint` functions
- Disable test mode in release pipeline and run examples
> [attestation] Fix mutual attestation

- cli/src/main.rs
- crypto/src/lib.rs
> [cli] Update Teaclave Command Line Tool so it can output cmac

- file_agent/README.md
- rpc/README.md
- services/README.md
- tests/README.md
> [docs] fix some typos

- COMMUNITY.md
- CONTRIBUTING.md
- CONTRIBUTORS.md
- README.md
- runtime/README.md
- sdk/README.md
- services/README.md
> Add docs for community, clitent SDK, and runtime

- .drone.yml
- cmake/UtilTargets.cmake
- docker/build.ubuntu-1804.sgx-2.9.1.Dockerfile
- docker/build.ubuntu-1804.sgx-dcap-1.6.Dockerfile
- examples/python/builtin_echo.py
- examples/python/builtin_gbdt_train.py
- examples/python/builtin_online_decrypt.py
- examples/python/mesapy_echo.py
- sdk/python/teaclave.py
- Annotation type for APIs (PEP484)
- Add docstring
This will be used to generate doc of Client SDK automatically.
> Add docs for Client SDK in Python

- rpc/Cargo.toml
- rpc/src/config.rs
- rpc/src/utils.rs
Fix build error when app depend teaclave_proto
> Fix rpc build error for app mode

- .gitignore
- README.md
- cmake/tomls/Cargo.sgx_trusted_lib.toml
- cmake/tomls/Cargo.sgx_untrusted_app.toml
- docs/README.md
- docs/development-tips.md
- Add development tips to use IDEs (RLS/rust-analyzer)
> Add development tips to use IDEs (RLS/rust-analyzer)

- docker/teaclave-rt.ubuntu-1804.Dockerfile
> fix sgx sdk path.

- docs/builtin-functions.md
- docs/development-tips.md
- docs/my-first-function.md
- docs/rust-guideline.md
Small grammar and typo fixes in the general documentation.
- documentation fix
Not, since only documentation files are updated.
> Small grammar and typo fixes in the documentation

- CONTRIBUTORS.md
- README.md
- binder/README.md
- common/README.md
- crypto/README.md
- docs/README.md
- types/README.md
> Add more docs

- README.md
- docs/README.md
- docs/functions-in-python.md
- Add a tutorial of writing functions in Python
> Add a tutorial of writing functions in Python

- cli/src/main.rs
- crypto/src/lib.rs
CI: http://ci.mesalock-linux.org/qinkunbao/incubator-teaclave/66
> [crypto] Read/Write files as small chunks

- tool/app/src/main.rs
Detect intel_sgx kernel module in the Teaclave SGX tool.
Fixes #382
> Detect intel_sgx kernel module

- common/README.md
- docs/README.md
- docs/build-system.md
- tool/README.md
- types/README.md
Fix links in the documents for website.
> Fix document links

- docs/development-tips.md
- services/access_control/app/src/main.rs
- services/authentication/app/src/main.rs
- services/execution/app/src/main.rs
- services/frontend/app/src/main.rs
- services/management/app/src/main.rs
- services/scheduler/app/src/main.rs
- services/storage/app/src/main.rs
- services/utils/service_enclave_utils/src/lib.rs
- tests/functional/app/src/main.rs
- tests/integration/app/src/main.rs
- tests/unit/app/src/main.rs
- tool/app/src/main.rs
- Polish the logging logic and document the usages
> Polish the logging logic and document the usages

- README.md
- docs/README.md
- docs/service-internals.md
- services/README.md
Add a document on service design and implementation internals.
> Add a document on service design and implementation details

- docs/README.md
> Fix a broken link

- COMMUNITY.md
- CONTRIBUTORS.md
- README.md
- docs/README.md
- docs/papers-talks.md
- Update docs: contributors, community projects, papers and talks.
> Update docs: contributors, community projects, papers and talks

- CONTRIBUTORS.md
- docs/papers-talks.md
> Fix formating issues

- SECURITY.md
Add an instruction to report security issues.
> Add instruction to report security issue

- KEYS
- Add my public key to KEYS for release code signing.
> Add KEYS for code signing

- DISCLAIMER
- DISCLAIMER-WIP
Use `DISCLAIMER-WIP` to disclaim potential issues.
> Use DISCLAIMER-WIP

- CMakeLists.txt
- cmake/TeaclaveGenVars.cmake
- cmake/TeaclaveUtils.cmake
- cmake/UtilTargets.cmake
- cmake/scripts/cargo_build_ex.sh
- cmake/scripts/cc_wrapper.sh
- cmake/scripts/gen_cov.sh
- cmake/scripts/gen_enclave_info_toml.py
- cmake/scripts/gen_enclave_sig.sh
- cmake/scripts/lcov_realpath.py
- cmake/scripts/llvm-gcov.sh
- cmake/scripts/parse_cargo_packages.py
- cmake/scripts/prep.sh
- cmake/scripts/rustc_wrapper.sh
- cmake/scripts/setup_cmake_tomls.py
- cmake/scripts/sgx_link_sign.sh
- cmake/scripts/test.sh
- common/protected_fs_rs/Cargo.toml
- examples/python/builtin_echo.py
- examples/python/builtin_face_detection.py
- examples/python/builtin_gbdt_train.py
- examples/python/builtin_online_decrypt.py
- examples/python/builtin_ordered_set_intersect.py
- examples/python/builtin_private_join_and_compute.py
- examples/python/builtin_rsa_sign.py
- examples/python/mesapy_echo.py
- examples/python/mesapy_logistic_reg.py
- examples/python/utils.py
- sdk/python/teaclave.py
- services/utils/service_enclave_utils/proc_macro/Cargo.toml
- Add license header to *.sh and *.py and change version number to 0.1.0
> Add license header and change version number to 0.1.0

- cmake/scripts/gen_enclave_sig.sh
- tool/app/src/main.rs
- tool/enclave/src/lib.rs
Print out error messages instead of logging for the sgx tool.
> Print out error messages instead of logging for the sgx tool

- cli/README.md
- cli/src/main.rs
- examples/python/builtin_rsa_sign.py
- Add examples in the CLI's readme.
> Add examples in the CLI's document

- cmake/scripts/prep.sh
Fix building issue when source is not in the git repo.
> Fix building issue when source is not in the git repo

- binder/Cargo.toml
- binder/src/binder.rs
- binder/src/ipc/app.rs
- binder/src/ipc/mod.rs
- binder/src/macros.rs
- tests/unit/app/Cargo.toml
- tests/unit/app/src/main.rs
- types/src/error.rs
> [binder] Add checks and test case for input/output buffer.

- CONTRIBUTORS.md
> Add new committers

- binder/README.md
- crypto/README.md
Add permlink for codebase's README.
> [docs] Add permlink for codebase's README

- README.md
- docs/README.md
- docs/my-first-function.md
- Polish highlights
- Add notes for building with Docker for Mac
> Polish document

- COMMUNITY.md
[Veracruz](https://github.com/veracruz-project/veracruz) is a framework for defining and deploying collaborative, privacy-preserving computations amongst a group of mutually mistrusting individuals.
Veracruz is using Teaclave SGX SDK to build up the framework and going to join the Confidential Computing Consortium: https://confidentialcomputing.io/projects/.
> [community] Add Veracruz

- COMMUNITY.md
> Fix typo in the mailing list

- COMMUNITY.md
This will also be included in the generated homepage.
> Add instruction to report security issue in the community page

- README.md
> [Fix] broken api reference links

- docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
Make container names consistent.
> Fix sim mode docker compose file

- docs/my-first-function.md
People may forget to install the Python modules when directly read the step by step instruction in the doc.
> Improve the step by step instruction for simulation mode

- services/proto/build.rs
> Don't use offline to build the proto when not within Teaclave's build system

- .github/ISSUE_TEMPLATE/blank_issue.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/report_bug.md
This will help new issue reports more structured and better categorized.
> Add GitHub issue templates

- common/protected_fs_rs/build.rs
- common/protected_fs_rs/protected_fs_c/CMakeLists.txt
- common/protected_fs_rs/protected_fs_c/README.md
- common/protected_fs_rs/protected_fs_c/build.sh
- common/protected_fs_rs/protected_fs_c/inc/non_sgx_protected_fs.h
- common/protected_fs_rs/protected_fs_c/ios.toolchain.cmake
- common/protected_fs_rs/protected_fs_c/sgx_uprotected_fs/sgx_uprotected_fs.cpp
- licenses/LICENSE-ios-cmake.txt
[format] make format
[SDK] Fix protected_fs linux build
Add ios cmake license.
- [ x ] New feature (non-breaking change which adds functionality)
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/369
> [SDK] Add iOS/macOS build support for protected_fs

- .github/workflows/ci.yml
- common/protected_fs_rs/build.rs
- common/protected_fs_rs/protected_fs_c/build.sh
- Fix SDK building issue on macos
- Enable macos CI job for client SDK
> Fix SDK building issue on macos and enable macos CI job for client SDK

- sdk/c/teaclave_client_sdk.h
- sdk/rust/src/bindings.rs
Add doc of functions in C bindings.
> Add doc of functions in C bindings

- cmake/scripts/test.sh
- examples/rust/builtin_echo/Cargo.toml
- examples/rust/builtin_echo/src/main.rs
- examples/rust/builtin_ordered_set_intersect/Cargo.toml
- examples/rust/builtin_ordered_set_intersect/src/main.rs
> Rust sdk example

- examples/c/Makefile
- examples/c/builtin_ordered_set_intersect.c
> Add C builtin example.

- examples/c/builtin_echo.c
- examples/c/builtin_ordered_set_intersect.c
> Update serialized requests in C builtin examples.

- sdk/swift/README.md
- sdk/swift/TeaclaveClientSDK/External/teaclave_client_sdk.h
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDK.podspec
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDK.xcodeproj/project.pbxproj
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDK.xcodeproj/xcshareddata/xcschemes/TeaclaveClientSDK.xcscheme
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDK.xcodeproj/xcshareddata/xcschemes/TeaclaveClientSDKTests.xcscheme
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDK/TeaclaveClientSDK.swift
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDKTests/TeaclaveClientSDKTests.swift
- make structs and functions public
- create `podspec` to distribute the framework
- add readme with a simple usage instruction
> Polishing Teaclave Client SDK for iOS

- examples/c/builtin_echo.c
- examples/c/builtin_ordered_set_intersect.c
- examples/python/builtin_gbdt_train.py
- examples/python/builtin_ordered_set_intersect.py
- examples/python/builtin_password_check.py
- examples/python/builtin_private_join_and_compute.py
- examples/python/builtin_rsa_sign.py
- examples/python/mesapy_logistic_reg.py
- sdk/python/teaclave.py
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDK/TeaclaveClientSDK.swift
- sdk/swift/TeaclaveClientSDK/TeaclaveClientSDKTests/TeaclaveClientSDKTests.swift
- services/proto/src/proto/teaclave_common.proto
- services/proto/src/proto/teaclave_frontend_service.proto
- services/proto/src/teaclave_frontend_service.rs
- types/src/crypto.rs
- types/src/task.rs
> Update cmac format from string to bytes array.

- NOTICE
Change the year of copyright to 2021
> Change the year of copyright to 2021

- services/access_control/app/src/main.rs
- services/authentication/app/src/main.rs
- services/execution/app/src/main.rs
- services/frontend/app/src/main.rs
- services/management/app/src/main.rs
- services/scheduler/app/src/main.rs
- services/storage/app/src/main.rs
- services/utils/service_app_utils/src/lib.rs
> Unify the launch of teaclave services

- CONTRIBUTORS.md
Add recent contributors to the `CONTRIBUTORS.md` file.
> Add recent contributors

- docs/adding-executors.md
correct an error of link in doc
> correct an error in doc

- CMakeLists.txt
- cmake/TeaclaveUtils.cmake
Fix some building issues introduced by WAMR cmake changes.
> Fix some building issues

- services/storage/enclave/src/service.rs
> Fix a potential index overflow of DBQueue

- README.md
- docs/README.md
- executor/src/wamr.rs
add deinstantiate for WAMR executor, deploy docs
> add deinstantiate for WAMR executor, deploy docs

- docs/access-control.md
- docs/executing-wasm.md
- third_party/README.md
> correct some documents

- CONTRIBUTORS.md
[Welcome Gordon.](https://lists.apache.org/thread.html/r8234c07b9b66bca00e62c07b8e64e41f9cbd24cae5ad4ed92bebfb06%40%3Cdev.teaclave.apache.org%3E)
> Add Gordon in the mentor list

- docker/teaclave-rt.ubuntu-1804.Dockerfile
Update the SGX SDK used in the dockerfile
Fixes #531
> [Bugfix] Update the SGX SDK used in the dockerfile

- docker/build.ubuntu-1804.sgx-2.14.Dockerfile
- docker/build.ubuntu-1804.sgx-dcap-1.11.Dockerfile
integrate pre-built TVM in the dokcer image for faster CI. Users can also use the image to build their own TVM functions.
> integrate pre-built TVM in the dokcer image

- .drone.yml
- .github/workflows/ci.yml
update CI image and add TVM example build
> update CI image and add TVM example build

- docs/development-tips.md
- scripts/ide.sh
polish ide script and tip doc
previous script doesn't update the content of .cargo/config
> polish ide script and tip doc

- sdk/rust/src/lib.rs
- services/execution/enclave/src/service.rs
- services/management/enclave/src/service.rs
- services/proto/src/teaclave_frontend_service.rs
- services/proto/src/teaclave_management_service.rs
- tests/functional/enclave/src/end_to_end/builtin_echo.rs
- tests/functional/enclave/src/end_to_end/builtin_gbdt_train.rs
- tests/functional/enclave/src/end_to_end/mesapy_data_fusion.rs
- tests/functional/enclave/src/end_to_end/mesapy_echo.rs
- tests/functional/enclave/src/execution_service.rs
- tests/functional/enclave/src/management_service.rs
- tests/functional/enclave/src/scheduler_service.rs
- tests/integration/enclave/src/teaclave_worker.rs
- types/src/function.rs
- types/src/staged_function.rs
- types/src/staged_task.rs
Some data structures are complicated to construct, due to their construction needing:
- a large number of inputs
- compound data (e.g. slices)
- optional configuration data
- choice between several flavors
which can easily lead to a large number of distinct constructors with many arguments each.
If `T` is such a data structure, consider introducing a `T` builder.
Refer to https://doc.rust-lang.org/1.0.0/style/ownership/builders.html and https://rust-unofficial.github.io/patterns/patterns/creational/builder.html for more information.
Locally and in CI.
> Use struture builder to construct complicated structures

- README.md
- docs/README.md
- docs/inference-with-tvm.md
> add TVM example document

- .github/workflows/ci.yml
Build cargo-lipo with the stable rust.
> Build cargo-lipo with the stable rust

- executor/src/wamr.rs
This PR fixes the resource leaks in WAMR.
https://github.com/bytecodealliance/wasm-micro-runtime/blob/51a00a4c2b60e50ae76ccd54c9f0db1c23555168/product-mini/platforms/posix/main.c#L443
runtime -> a computer
module -> a program
module instance -> a process
The previous implementation only destroys the module instance but fails to destroy the runtime and the module.
-  Bug fix (non-breaking change which fixes an issue)
> [WAMR] Fix leaked resources

- cmake/scripts/sgx_link_sign.sh
Enable RELRO and non-executable stack in linking to enhance security.
CI test.
> Add security link flags

- services/frontend/enclave/src/lib.rs
- services/frontend/enclave/src/service.rs
- services/management/enclave/src/lib.rs
- services/management/enclave/src/service.rs
- services/scheduler/enclave/src/lib.rs
- services/scheduler/enclave/src/service.rs
- services/storage/enclave/src/lib.rs
Add Service launching in logs and reconnecting warnings.
> [Add] Service launching in logs and reconnecting warnings.

- services/storage/enclave/src/service.rs
Enable compact_range to reduce LevelDB disk usage in persistent mode.
We also invoke db.flush for all put/delete operations.
> [Mod] Flush DB and compact_range after dequeue operation.

- services/utils/service_enclave_utils/src/lib.rs
Add debug log to print `g_peak_heap_used` and `g_peak_rsrv_mem_committed`.
CI.
> Log g_peak_heap_used and g_peak_rsrv_mem_committed when finalizing

- dcap/src/main.rs
Fix DCAP verification concurrency issue by introducing a global lock. It seems the "sgx_qv_verify_quote" logic breaks (return SGX_QL_ERROR_UNEXPECTED or  collateral_exp_status==1) when there are concurrent verification request.
I need some time to figure out the root cause.
> [Fix] DCAP service error.

- common/rusty_leveldb_sgx/src/log.rs
When the DB is in persistent mode, DB's log files are read back to memory every time after DB restarts. However, some log records might cause the Log Reader's offset to grow larger than the block size.
This PR changed tolerate this corner case by resetting the offset to 0. As each record checks its own checksum during loading, this modification would not introduce data inconsistent issues.
Another modification in this PR is optimizing the log writer logic. Instead of multiple file-writes for a single record, we use a temporal vector to hold the whole record and write the complete buffer to file in a single write operation.
> [Fix] Improve log writer and tolerate  log reader

- CMakeLists.txt
- cmake/TeaclaveUtils.cmake
This PR fix building issue.
According to https://github.com/rust-lang/cargo/issues/2904, I enabled cargo log with `CARGO_LOG=cargo::core::compiler::fingerprint=trace` and see this log:
```
[2021-12-14T02:19:39Z INFO  cargo::core::compiler::fingerprint]     err: RUSTFLAGS has changed: ["--cfg", "test_mode", "--cfg", "sgx_sim", "--cfg", "executor_builtin", "--cfg", "executor_mesapy", "--cfg", "executor_wamr", "--cfg", "test_mode"] != ["--cfg", "test_mode", "--cfg", "sgx_sim", "--cfg", "executor_builtin", "--cfg", "executor_mesapy", "--cfg", "executor_wamr"]
```
I realize that this additional `test_mode` flag affect the rebuild. However, when building with `TEST_MODE=ON`, the `test_mode` flag has been added to all services. Therefore, we can safely delete this.
CI.
> Fix packages rebuild every time

- examples/python/builtin_echo.py
- examples/python/builtin_face_detection.py
- examples/python/builtin_gbdt_train.py
- examples/python/builtin_online_decrypt.py
- examples/python/builtin_ordered_set_intersect.py
- examples/python/builtin_password_check.py
- examples/python/builtin_private_join_and_compute.py
- examples/python/builtin_rsa_sign.py
- examples/python/mesapy_echo.py
- examples/python/mesapy_logistic_reg.py
- examples/python/utils.py
- examples/python/wasm_c_simple_add.py
- examples/python/wasm_rust_psi.py
- examples/python/wasm_tvm_mnist.py
- sdk/python/teaclave.py
Refactor Python client SDK. There are several changes:
- Add TeacalveException, raise when needed
- Add close channel function and support context manager functions (i.e., `with xxx as:`)
- Remove client classes and merge all functions into the service classes
- Add a parent class (`TeaclaveService`) to merge common APIs in service class
CI tests.
> Refactor Python client SDK

- services/management/enclave/src/service.rs
Fix list functions only show the latest function id
CI test.
> Fix list functions only show the latest function id

- sdk/python/teaclave.py
Inherent Request class for proper json serde.
CI test.
> Inherent Request class for proper json serde

- cmake/TeaclaveUtils.cmake
> Do not generate enclave_info when building teaclave_sgx_tool

- .drone.yml
- cmake/scripts/test.sh
- file_agent/src/agent.rs
This PR add a new pipeline and also fix a concurrent issue of testing.
https://ci.mesalock-linux.org/mssun/incubator-teaclave/131
> Add Ubuntu 20.04 pipeline to CI and fix testing concurrent issue

- examples/python/wasm_tvm_mnist_payload/Makefile
Export TVM_HOME env var for prebuilt tvm-sys
> Export TVM_HOME env var for prebuilt tvm-sys

- examples/python/mesapy_deadloop_cancel.py
- sdk/python/teaclave.py
The execution service will only be terminated if the task status is `Running`. This PR fixes the test in `mesapy_deadloop_cancel.py`.
> [test] fix cancel task tests

- scripts/ide.sh
fix ide scripts; users can run ide.sh from any cwd
> fix ide scripts; users can run ide.sh from any cwd

- .drone.yml
- .github/workflows/ci.yml
- docker/build.ubuntu-1804.sgx-2.14.Dockerfile
- docker/build.ubuntu-1804.sgx-dcap-1.11.Dockerfile
Pin pyopenssl version for 1804 docker to avoid compatibility issue.
CI tests: https://ci.mesalock-linux.org/mssun/incubator-teaclave/138
> Pin pyopenssl version for 1804 docker

- .gitmodules
Update WAMR version to WAMR-01-18-2022
Sync upstream.
https://ci.mesalock-linux.org/mssun/incubator-teaclave/140
> Update WAMR version to WAMR-01-18-2022

- sdk/python/teaclave.py
Fix certification verification issue.
https://ci.mesalock-linux.org/mssun/incubator-teaclave/145
> Fix certification verification issue

- services/authentication/enclave/src/api_service.rs
- services/authentication/enclave/src/error.rs
- services/authentication/enclave/src/internal_service.rs
- tests/scripts/functional_tests.py
The current error handling is a bit confused. I suggest to use the following implementation conventions. Let's use the authentication service as an example:
- `AuthenticationServiceError`: errors that will be propagated to the end users
Error handling refactoring.
> Polish authentication error

- services/frontend/enclave/src/error.rs
- services/frontend/enclave/src/service.rs
Make frontend error more precise to end users.
Code polishing.
https://ci.mesalock-linux.org/mssun/incubator-teaclave/149/
> Polish frontend error

- sdk/python/teaclave.py
> Fix typos in sdk

- services/execution/enclave/src/task_file_manager.rs
- types/src/staged_file.rs
> [Add] Support AES-GCM output files.

- sdk/python/teaclave.py
This PR removes some magic numbers in Teaclave Python SDK.
> Update teaclave SDK

- sdk/python/teaclave.py
Fix a message typo of TeaclaveException in teaclave.py
> Fix a message typo of TeaclaveException

- examples/python/wasm_tvm_mnist_payload/test_lib.py
- services/access_control/python/acs_engine_test.py
There are several unclosed files in 2 python script files.
> Fix unclosed files in pyscripts

- cmake/scripts/test.sh
- services/management/enclave/src/service.rs
- services/proto/src/proto/teaclave_storage_service.proto
- services/proto/src/teaclave_storage_service.rs
- services/storage/enclave/src/lib.rs
- services/storage/enclave/src/service.rs
- tests/functional/enclave/src/management_service.rs
Fix privilege issues.
- fix inconsistency of GetFunction and ListFunctions interfaces
- add GetKeysByPrefix interface to the storage service to help the fix
Fixes #624
- CI test: https://ci.mesalock-linux.org/mssun/incubator-teaclave/159
- new test cases
> Fix privilege issue

- examples/python/mesapy_deadloop_cancel.py
- services/management/enclave/src/error.rs
- services/management/enclave/src/service.rs
Better task state error and fix cancel error issue in the example.
CI: https://ci.mesalock-linux.org/mssun/incubator-teaclave/161
> Better task state error and fix cancel error issue in the example

- README.md
- docs/README.md
- docs/release-guide.md
Add a release guide to help releasing Apache versions in the future.
N/A
> Add release guide in docs

- docs/release-guide.md
Fix some minor issues in the release guide document.
> Fix release guide

- NOTICE
Update copyright year to 2022.
> Update copyright year to 2022

- .github/workflows/ci.yml
- .github/workflows/ubuntu1804-test.yml
- .github/workflows/ubuntu2004-test.yml
- CMakeLists.txt
- cmake/scripts/build_in_ci.sh
- cmake/scripts/test.sh
> Improve CI

- .licenserc.yaml
Ignore license check for txt files.
> Ignore license check for txt files

- common/rusty_leveldb_sgx/src/db_impl.rs
- common/rusty_leveldb_sgx/src/types.rs
- sdk/rust/src/bindings.rs
Tests running in ubuntu18.04 container image raised an [error](https://github.com/apache/incubator-teaclave/actions/runs/3381637780/jobs/5615754041).
Another bug of the rust sdk binding was reported by @GeminiCarrie .
> Bugfix of leveldb and rust sdk

- sdk/python/teaclave.py
Putting the arguments in different lines improves readability.
> Improve function comment layout for pdoc

- sdk/python/teaclave.py
The fix is reported from https://github.com/mithril-security/poison-tea.
Fix an attestation bypass attack reported from https://github.com/mithril-security/poison-tea.
> Check the binding of the server certificate with the sgx quote

- examples/rust/builtin_echo/Cargo.lock
- examples/rust/builtin_echo/Cargo.toml
- examples/rust/builtin_ordered_set_intersect/Cargo.lock
- examples/rust/builtin_ordered_set_intersect/Cargo.toml
- sdk/rust/Cargo.lock
- sdk/rust/Cargo.toml
> Bump h2 from 0.3.16 to 0.3.19

- README.md
- docs/README.md
- examples/python/wasm_tvm_mnist_payload/Cargo.toml
- services/management/enclave/src/service.rs
- services/proto/src/teaclave_frontend_service.rs
- tests/functional/enclave/src/management_service.rs
> Polish access control in manager

- crates/README.md
- sgx/README.md
- trustzone/README.md
- website-toc.md
Add website-toc.md for website display.
> docs: add website-toc for website display.

- .asf.yaml
update project label to reflect the latest status.
> config: update labels in .asf.yaml
