examples/online_decrypt/Cargo.toml
examples/online_decrypt/src/main.rs
mesatee_core/Cargo.toml
mesatee_core/src/rpc/sgx/auth.rs
mesatee_core/src/rpc/sgx/utils.rs
mesatee_services/fns/sgx_trusted_lib/Cargo.toml
mesatee_services/fns/sgx_trusted_lib/src/trusted_worker/online_decrypt.rs
mesatee_services/tdfs/external/client/Cargo.toml
mesatee_services/tdfs/internal/client/Cargo.toml
mesatee_services/tdfs/internal/client/src/file_util.rs
tests/integration_test/Cargo.toml
toolchain_deps/Cargo.sgx_trusted_lib.toml

Upgrade dependencies. Major changes include: 
- ring => 0.16.5
- rustls => 0.16
- webpki => 0.21.0
- webpki-roots => 0.17.0
For the whole list, please access the [diff](https://github.com/mesalock-linux/crates-sgx/commit/a9462e3f2e95878e8dff931ff8ac9a75579dc6c1#diff-26fd799ea07494916e9da9b91b2aac64).
Completed all CI tests.

Upgrade dependencies

---

toolchain_deps/Cargo.sgx_trusted_lib.toml

Old sgx_unwind contains unnecessary source files which should be excluded. This commit fix the sgx_unwind build problem, as well as update third party libraries.
Fixes #29

Fix 16.04 building problem and upgrade third party crates

---

mesatee_cli/Cargo.toml

Delete the profile section to fix build warnings like this:
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
```
No need to test.

mesatee_cli: delete the profile section to fix build warnings

---

CMakeLists.txt
Makefile
examples/py_matrix_multiply/payload.py
examples/py_matrix_multiply/py_matrix_multiply.sh
mesatee_services/fns/sgx_trusted_lib/src/trusted_worker/mesapy.rs
tests/integration_test/src/mesapy.rs

Support passing arguments (context_id, context_token) for the mesapy worker. This is the first step to have more context related APIs in MesaPy.
The argument passing function has been tested in MesaPy. The functional tests of mesapy's context-related APIs will be added after completing the implementation.

mesapy_exec: pass args (context_id, context_token) for the mesapy worker

---

examples/kmeans/kmeans_demo.sh

Disable assertion for the Kmeans example. Since Kmeans randomly select initial points, the classification result may be different sometimes.
CI.

Disable assertion for K-means

---

cmake/scripts/cc_wrapper.sh
cmake/scripts/prep.sh
cmake/scripts/rustc_wrapper.sh

Create symlinks to make remapped paths accessible and avoid repeated building caused by num-traits.
/tmp/mesatee_symlinks/cargo_home
/tmp/mesatee_symlinks/mesatee_src
/tmp/mesatee_symlinks/mesatee_build
Yes

Fix repeated compilation

---

cmake/MesaTEEUtils.cmake
cmake/scripts/parse_cargo_packages.py

Improve parse_cargo_packages.py to fix the error when a high version Python3 is not available.
Add some description for the parse script.

Remove requirement of high version Python3

---

service.sh

Set default value of `MESATEE_CFG_DIR` in service.sh. `environment.deprecated` is no longer needed.
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/10

Set default value of MESATEE_CFG_DIR in service.sh

---

.drone.yml
cmake/scripts/sgx_test.sh
config.toml
docs/faq.md
docs/how_to_run.md
mesatee_config/src/runtime_config.rs
mesatee_core/src/rpc/sgx/ra.rs
mesatee_core/src/utils.rs

Current design of IAS configuration is not friendly to k8s. #80 discussed it. In this PR, I updated mesatee_config to acquire IAS key/spid from environment variables specified in `config.toml`. Updated CI scripts accordingly.
This is a **breaking change**. The previous configuration (ias_key.txt + ias_spid.txt) is deprecated.
Fixes #80 
CI script updated and passed. [proof](http://ci.mesalock-linux.org/dingelish/incubator-mesatee/18)

Use environment variable to configure IAS SPID/KEY

---

docs/how_to_build.md
mesatee_services/tdfs/sgx_trusted_lib/src/data_store.rs
tests/integration_test/test_data/test.toml

Introduce a new env var: `MESATEE_STORAGE_DIR`. This will be used to setup path for TDFS.
CI

Storage dir can be set by env var (MESATEE_STORAGE_DIR)

---

cmake/scripts/gen_cov.sh

Fix coverage testing error because of wrong path of llvm-gcov in gen_cov.sh .
Yes

Fix coverage testing error because of wrong path of llvm-gcov.

---

mesatee_utils/protected_fs_rs/protected_fs_c/CMakeLists.txt
mesatee_utils/protected_fs_rs/protected_fs_c/sgx_tprotected_fs/CMakeLists.txt
mesatee_utils/protected_fs_rs/protected_fs_c/sgx_uprotected_fs/CMakeLists.txt

Fix build failure on Ubuntu 16.04 environment.
The failure is caused by ineffective CMake build flags in previous commit.
CI passed. http://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/11

[Mod] fix cmake

---

cmake/UtilTargets.cmake
mesatee_services/kms/proto/build.rs
mesatee_services/kms/proto/src/prost_generated/kms_proto.rs

Exclude generated files for ```make format``` and ```make check```. All the files  under prost_generated will be excluded. 
Fixes #116 
Generated kms_proto will not be formated. Passed CI: http://ci.mesalock-linux.org/litongxin1991/incubator-mesatee/33/5/4
Other files will be formatted or checked. See this failed CI result: http://ci.mesalock-linux.org/litongxin1991/incubator-mesatee/32/1/3 
- [ X Make sure your code lints/format.

Exclude generated files for rustfmt

---

mesatee_services/tdfs/external/client/src/tdfs_client.rs
mesatee_services/tdfs/internal/client/src/file_util.rs
mesatee_services/tdfs/internal/client/src/tdfs_client.rs
mesatee_services/tdfs/sgx_trusted_lib/src/data_store.rs
tests/integration_test/test_data/test.toml

Use relative path in TDFS Server and RPC. TDFS client will construct an absolute path with environment variable ``` MESATEE_STORAGE_DIR```.  So different services/clients can configure and use different storage directory. 
Fixes #91 
Passed CI: http://ci.mesalock-linux.org/litongxin1991/incubator-mesatee/38/1/4
Passed ```make sgx-test``` locally with environment variable
```
MESATEE_STORAGE_DIR=/tmp/target_dir make sgx-test
```
No files generated in ```/tmp/```, files are generated in ```/tmp/target_dir```

use relative path in TDFS Server and RPC

---

mesatee_utils/protected_fs_rs/protected_fs_c/sgx_tprotected_fs.h
mesatee_utils/protected_fs_rs/protected_fs_c/sgx_tprotected_fs/file_other.cpp
mesatee_utils/protected_fs_rs/protected_fs_c/sgx_tprotected_fs/protected_fs_file.h
mesatee_utils/protected_fs_rs/protected_fs_c/sgx_tprotected_fs/sgx_tprotected_fs.cpp
mesatee_utils/protected_fs_rs/src/protected_fs.rs
mesatee_utils/protected_fs_rs/src/sgx_fs_inner.rs
mesatee_utils/protected_fs_rs/src/sgx_tprotected_fs.rs
mesatee_utils/protected_fs_rs/tests/rename.rs

When porting `rusty-leveldb` to MesaTEE, I found that the following features are missing for ProtectedFile. 
- Renaming file name in file meta.
- `read_at` function from random read.
This PR adds these two features. Later I will submit an another PR for leveldb-sgx library. 
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/37

Support more operations for ProtectedFile.

---

teaclave_cli/Cargo.toml
teaclave_cli/src/main.rs

`quicli` is not useful in `teaclave_cli` right now.
Fixes #169
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/158

[cli] Remove unneccessary dependency

---

docker/docker-compose-ubuntu-1604.yml
docker/docker-compose-ubuntu-1804.yml
docker/fns-rt.ubuntu-1604.Dockerfile
docker/fns-rt.ubuntu-1804.Dockerfile
docker/kms-rt.ubuntu-1604.Dockerfile
docker/kms-rt.ubuntu-1804.Dockerfile
docker/tdfs-rt.ubuntu-1604.Dockerfile
docker/tdfs-rt.ubuntu-1804.Dockerfile
docker/tms-rt.ubuntu-1604.Dockerfile
docker/tms-rt.ubuntu-1804.Dockerfile

Fix ubuntu 16.04 runtime docker building issue. I also remove the default `RUST_LOG` env, you can set when launching with the `docker-compose` by yourself.
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/213

[docker] Fix docker building issue

---

.asf.yaml

Use `.asf.yaml` to setup github repo. (refer to: https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories)

Add asf.yaml to setup description of github repo

---

CMakeLists.txt
cmake/MesaTEEUtils.cmake
cmake/UtilTargets.cmake
cmake/scripts/sgx_link_sign.sh
docs/how_to_build.md
mesatee_core/src/lib.rs
mesatee_services/acs/sgx_app/src/main.rs
mesatee_services/fns/sgx_app/src/main.rs
mesatee_services/tms/sgx_app/src/main.rs
teaclave_binder/src/binder.rs
tests/functional_test/sgx_app/src/main.rs

- Generate *_enclave.so instead of *.enclave.so for the convenience of symbol retrieving.
- Remove unused env MESATEE_TEST_MODE.
- Remove <build_dir> from target `check`.
- Fix format of mesatee_core/src/lib.rs.
Yes

Generate *_enclave.so instead of *.enclave.so

---

mesatee_core/src/rpc/sgx/client.rs
mesatee_core/src/rpc/sgx/mod.rs
mesatee_core/src/rpc/sgx/ra.rs
mesatee_core/src/rpc/sgx/server.rs
teaclave_config/build.config.toml
teaclave_config/config_gen/main.rs

Related to #61. I optimized the TLS config cache related logic with the following changes.
- Simplify `get_tls_config` logic, changed the hash_map cached structure.
- Introduce `private_key_sha256` as an identify to CertKeyPair, making `get_ra_cert` return a simple CertKeyPair.
- Decouple `ecc_handle`  from the params of `fn gen_ecc_cert`.
- Split the contruction of cert_der and private_key_der in to two different functions.
I am still working the optimization, and will finally fix #61 in a descent way. 
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/84

Optimize RPC TLS config

---

mesatee_core/src/lib.rs
mesatee_core/src/rpc/sgx/client.rs
mesatee_core/src/rpc/sgx/mod.rs
mesatee_core/src/rpc/sgx/ra.rs
mesatee_core/src/rpc/sgx/server.rs

This is a follow up of PR #190, and it finally resolves the issue of issue #61.
The RACache renewal logic is into two functions
- `ra::init_ra_credential` (returns a Result)
- This function is called during the enclave initialization phase, the inner RA error (if any) would finally propagated to `_core::init_service`.
- `ra::get_current_ra_credential()`  (always returns a RACredential)
- This function is called before each TLS handshake. If there is an inner RA error during the renewal process, we will not update the RACache. The existing (expired) RACredential is returned, which will lead to an TLS handshake error if the other side validate the target correctly.
https://ci.mesalock-linux.org/m4sterchain/incubator-mesatee/89

RA no more panic

---

mesatee_core/src/rpc/mod.rs
mesatee_core/src/rpc/server.rs
mesatee_core/src/rpc/sgx/mod.rs
mesatee_core/src/rpc/sgx/server.rs
mesatee_core/src/rpc/unix/mod.rs
mesatee_services/acs/sgx_trusted_lib/src/sgx.rs
mesatee_services/fns/sgx_trusted_lib/src/sgx/mod.rs
mesatee_services/kms/sgx_trusted_lib/src/sgx.rs
mesatee_services/tdfs/sgx_trusted_lib/src/sgx.rs
mesatee_services/tms/sgx_trusted_lib/src/sgx.rs

Add SgxTrustedServer in RPC.
Now, we finally have `SgxTrustedChannel` and `SgxTrustedServer`.
- `SgxTrustedChannel`: RPC client side struct
- `SgxTrustedServer`: RPC server side struct
Usage:
```rust
let server = SgxTrustedServer::new(ACSEnclave::default(), fd, enclave_attr)?;
// Ignore error
let _ = server.start();
```
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/257

[core] Add SgxTrustedServer in RPC

---

services/authentication/enclave/Cargo.toml
services/authentication/enclave/src/lib.rs
services/authentication/enclave/src/service.rs
services/authentication/enclave/src/user_db.rs
services/authentication/enclave/src/user_info.rs
services/database/enclave/src/service.rs
services/proto/src/proto/teaclave_authentication_service.proto
services/proto/src/teaclave_authentication_service.rs
services/proto/src/teaclave_database_service.rs
tests/functional_tests/enclave/src/teaclave_authentication_service.rs
tests/unit_tests/enclave/src/lib.rs

Simple authentication service:
1. use pbkdf2 to protect password
2. use rusty_leveldb to save password
3. use json web token to generate and verify authentication token

simple authentication service

---

common/protected_fs_rs/protected_fs_c/inc/non_sgx_protected_fs.h
common/protected_fs_rs/protected_fs_c/sgx_tprotected_fs/protected_fs_nodes.h

Make teaclave compatible with sgx 2.8.
This patch is backward-compatible.
To work under sgx 2.8, struct global_data_t needs to be patched for crates-io & crates-sgx.
Yes

Make teaclave compatible with sgx 2.8

---

attestation/src/attestation.rs
attestation/src/key.rs
attestation/src/platform.rs

The built-in ECDSA is based on NIST P-256 (a.k.a. secp256r1), not secp256k1. This PR just fix that typo~
Relevant line of codes is https://github.com/apache/incubator-teaclave/blob/develop/attestation/src/key.rs#L25 
- API change with a documentation update
Document changed only~

docs(attestation): fix a typo and add some doc

---

tests/functional/enclave/Cargo.toml
tests/functional/enclave/src/access_control_service.rs
tests/functional/enclave/src/authentication_service.rs
tests/functional/enclave/src/end_to_end/mesapy_echo.rs
tests/functional/enclave/src/end_to_end/mod.rs
tests/functional/enclave/src/end_to_end/native_echo.rs
tests/functional/enclave/src/end_to_end/native_gbdt_training.rs
tests/functional/enclave/src/execution_service.rs
tests/functional/enclave/src/frontend_service.rs
tests/functional/enclave/src/lib.rs
tests/functional/enclave/src/management_service.rs
tests/functional/enclave/src/scheduler_service.rs
tests/functional/enclave/src/storage_service.rs
tests/functional/enclave/src/utils.rs
tests/utils/Cargo.toml
tests/utils/proc_macro/Cargo.toml
tests/utils/proc_macro/src/lib.rs
tests/utils/src/lib.rs

- Introduce `[test_case]` to annotate a test case function.
- Introduce `run_inventory_tests!()` to run all registered test cases.
- Use `run_inventory_tests!(predicate)` where `predicate` is a closure with type `|&str| -> bool` to filter test cases. The first param is the full path of the registered test function.
- Functional test is rewritten with these helpers.
- `crates-sgx` and `crates-io` are also updated with `inventory` 0.1.6.
CI passed (https://ci.mesalock-linux.org/mssun/incubator-mesatee/680)

Automatic collect test cases into inventory and support to run with predicate

---

config/build.config.toml
config/build.rs
config/config_gen/Cargo.toml
services/proto/build.rs
services/proto/proto_gen/Cargo.toml

This PR makes building build.rs offline using vendored crates.
Fix #181
CI: https://ci.mesalock-linux.org/mssun/incubator-mesatee/725

Make building build.rs offline using vendored crates

---

DISCLAIMER

Fix disclaimer wording: "sponsored by the name of Apache Incubator PMC" => "sponsored by the Apache Incubator"

Fix wording

---

function/src/echo.rs
function/src/gbdt_train.rs
function/src/logistic_regression_train.rs
sdk/python/teaclave.py
services/execution/enclave/src/service.rs
services/management/enclave/src/service.rs
services/proto/src/proto/teaclave_frontend_service.proto
services/proto/src/teaclave_frontend_service.rs
tests/functional/enclave/src/end_to_end/builtin_gbdt_train.rs
tests/integration/enclave/src/teaclave_worker.rs
types/src/staged_function.rs

Use json type (`serde_json::Value`) for function arguments instead of string hashmap (`HashMap<String, String>`).
CI passed: https://ci.mesalock-linux.org/mssun/incubator-mesatee/799

Use json type for function arguments instead of string/string hashmap

---

README.md
docs/access-control.md

Some simple documentations explaining how Teaclave access control model works.

Add access control docs.

---

docs/access-control.md
docs/mutual-attestation.md
docs/threat-model.md
services/README.md

- Fix links in docs for website presentation
Note that when writing docs, if link to GitHub code or directories instead of `.md` files, please use absolute links of GitHub. Otherwise, the generated docs in website will not recognize the internal links to code resulting in broken links.

[docs] Fix links in docs for website presentation

---

cmake/TeaclaveGenVars.cmake

- This will cause failure of `should_panic` (`catch_unwind`) in current toolchain.

[cmake] Remove -Zno-landing-pads in RUSTFLAGS for coverage

---

crypto/src/lib.rs

The previous implementation may output incorrect auth_tag values. I tested the current implementation with several files, including an end-to-end example (PSI).

fix a bug that may output incorrect cmac values for small files

---

cli/Cargo.toml
cli/README.md
cli/src/main.rs
cmake/scripts/test.sh
examples/python/utils.py

- Add a sub-command for clients to verify signatures before using the enclave info to connect the platform.

[cli] Add verify subcommand to verify enclave info signatures

---

attestation/Cargo.toml
binder/Cargo.toml
cmake/UtilTargets.cmake
cmake/scripts/cargo_build_ex.sh
common/protected_fs_rs/Cargo.toml
docs/build-system.md
executor/Cargo.toml
file_agent/Cargo.toml
function/Cargo.toml
rpc/Cargo.toml
runtime/Cargo.toml
services/access_control/enclave/Cargo.toml
services/execution/enclave/Cargo.toml
services/frontend/enclave/Cargo.toml
services/management/enclave/Cargo.toml
services/proto/Cargo.toml
services/utils/service_enclave_utils/Cargo.toml
types/Cargo.toml
worker/Cargo.toml

- Add the `make doc` target to generate docs of crates in Teaclave.
- To support it, some dependencies are fixed in `Cargo.toml` (features and optional).
- Document this in the build system doc.
CI passed: https://ci.mesalock-linux.org/mssun/incubator-mesatee/946

Add the make doc target to generate docs of crates in Teaclave

---

file_agent/src/agent.rs

Change write method to write_all, in order to fix downloading large remote input file bug.
According to [tokio doc](https://docs.rs/tokio/0.1.22/tokio/prelude/trait.Write.html), method write cannot guarantee writing the whole buffer, but method write_all will continuously call write until there is no more data to be written or an error of non-ErrorKind::Interrupted kind is returned.

fix downloading large remote input file bug

---

rpc/src/protocol.rs

Replace unsafe&transmute with primitives::to_be_bytes after Rust 1.32

---

docker/docker-compose-ubuntu-1804.yml
rpc/src/protocol.rs
sdk/python/teaclave.py
services/access_control/enclave/Enclave.config.xml
services/authentication/enclave/Enclave.config.xml
services/execution/enclave/Enclave.config.xml
services/frontend/enclave/Enclave.config.xml
services/management/enclave/Enclave.config.xml
services/scheduler/enclave/Enclave.config.xml
services/storage/enclave/Enclave.config.xml

- Increase the default heap size of enclaves to 256M.
- Fix recv/send in the Python client SDK.

Increase heap size of enclave

---

examples/python/mesapy_echo.py

Without explicitly specifying the name of the argument, the value `message` will pass to `payload_file`, not `message`.
CI: http://ci.mesalock-linux.org/qinkunbao/incubator-teaclave/70/1/5

fix the echo example

---

examples/python/builtin_face_detection.py
function/src/face_detection.rs

- Use byte array instead of base64

Use byte array instead of base64 for image transfer making parsing faster

---

binder/src/binder.rs
cmake/scripts/Enclave.lds
services/access_control/app/src/main.rs
services/authentication/app/src/main.rs
services/execution/app/src/main.rs
services/frontend/app/src/main.rs
services/management/app/src/main.rs
services/scheduler/app/src/main.rs
services/storage/app/src/main.rs
services/utils/service_app_utils/src/lib.rs

When receiving singals like SIGTERM, SIGINT, the services will be terminated immediately. Before exiting the process, we force to call enclave destroy. This will help us to collect sgx_emmt information if needed.
Also, two global variables are added for profiling memory usage.

Force to call enclave destory when receiving signals

---

CMakeLists.txt
cmake/scripts/prep.sh
docs/build-system.md

- Add an option to the build system: use `USE_PREBUILT_MESAPY` to config whether to use the prebuilt library.

Use USE_PREBUILT_MESAPY to config whether to use the prebuilt library

---

README.md
docker/README.md
docker/docker-compose-ubuntu-1804-intel-sgx.yml
docker/docker-compose-ubuntu-1804-isgx.yml
docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
docs/README.md
docs/azure-confidential-computing.md
docs/my-first-function.md

- Add document
- Split docker-compose files into three for `isgx` driver, `intel_sgx` driver and simulation mode.
- Polish the My First Function document

[docs] Add document of Deploying Teaclave on Azure Confidential Computing Virtual Machines

---

attestation/src/report.rs
cli/Cargo.toml
cli/README.md
cli/src/main.rs

Add a subcommand of `teaclave_cli`.
Here is an example of the usage.
```
$ ./teaclave_cli attest --address accvm-dev:7776 --as-ca-cert ../../keys/ias_root_ca_cert.pem
Report Freshness: 1854s
SGX Quote status: SwHardeningNeeded
Version and signature/key type: Version 2, EPID Linkable signature
GID or reserved: 3014
Security version of the QE: 11
Security version of the PCE: 10
ID of the QE vendor: 00000000-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Custom user-defined data (hex): 75b6024c00000000000000000000000000000000
CPU version (hex): 0f0f0305ff8006000000000000000000
SSA Frame extended feature set: 0
Attributes of the enclave (hex): 07000000000000000700000000000000
Enclave measurement (hex): eadeb5537962d2451a8619fb6a4b10b72f56479e0b7db0bb9c3f5edc143ca6eb
Hash of the enclave singing key (hex): …
```

[cli] Add the attest subcommand to display attestation report

---

docs/azure-confidential-computing.md
docs/my-first-function.md

`libcurl4-openssldev` is a typo of `libcurl4-openssl-dev`- https://packages.debian.org/jessie/libcurl4-openssl-dev
Use the right spelling
Doc, not need for testing

Correct `libcurl4-openssldev` in the doc

---

docker/README.md
docker/docker-compose-ubuntu-1804-intel-sgx.yml
docker/docker-compose-ubuntu-1804-isgx.yml
docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
docker/docker-compose-ubuntu-1804.yml

This can help people to run examples with registered input files.

Add a teaclave-file-service container to the docker compose file

---

cmake/scripts/test.sh
examples/c/.clang-format
examples/c/Makefile
examples/c/builtin_echo.c
sdk/c/Makefile
sdk/c/cbindgen.toml
sdk/c/teaclave_client_sdk.h
sdk/rust/Cargo.toml
sdk/rust/src/bindings.rs
sdk/rust/src/lib.rs

Introduce C client SDK. There are two types of C APIs:
- `*_serialized` APIs accept JSON serialized string requests and responses. These APIs is for other high level programming languages.
- Normal APIs like `teaclave_user_login`.
An echo example using C client SDK is also implemented. Client APIs will be documented later when all useful languages are properly implemented.
CI passed: http://ci.mesalock-linux.org/mssun/incubator-mesatee/1131

C client SDK

---

.github/workflows/ci.yml

Previously we have in-house CI (Drone CI). However, this is not public to all contributors. This PR is start to use GitHub Action.  There are three jobs: building/testing in simulation mode, code format, code linting. It takes about 30 minutes in GitHub Action. Though it's slow. It's better than nothing.
Since GitHub Action doesn't have SGX machine, we will consider to use self-host runners for GitHub later.

Start to use GitHub Actions

---

CMakeLists.txt
cmake/TeaclaveUtils.cmake
cmake/tomls/Cargo.unix_app.toml
docs/build-system.md
sdk/c/cbindgen.toml
sdk/rust/Cargo.toml

Integrate teaclave_client_sdk to the build system. Now you can use `make teaclave_client_sdk` to build the dynamic and staitc library of client sdk.

Integrate teaclave_client_sdk to the build system

---

examples/README.md

Add instruction to config URLs of input/output files in examples.
Fixes #458

Add instruction to config URLs of input/output files in examples

---

common/protected_fs_rs/protected_fs_c/build.sh
docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml

Make container names consistent with other docker-compose files.
Fixes #495, #463.

Make container names consistent with other docker-compose files

---

docs/access-control.md

Just a typo fix
- Document typo fix

Fix a typo of data_owner

---

CMakeLists.txt

Fix an issue about `Python.h not found` when compiling `acs_py_enclave.c`
Fixes # (526)
- [ X] Bug fix (non-breaking change which fixes an issue)
`cmake -DTEST_MODE=ON ..`
`make`

Fix a compiling issue (#526)

---

docs/development-tips.md

Fix a minor typo issue in `development-tips.md`
`parth::to::module=level => path::to::module=level`
Fixes #528

A minor typo fixes in development doc. (#528)

---

docker/teaclave-rt.ubuntu-1804.Dockerfile

Teaclave compliains at runtime: `error while loading shared libraries: libsgx_uae_service.so: cannot open shared object file: No such file or directory` if `uae` is not installed.

[Bugfix] add uae download in dockerfile

---

docs/executing-wasm.md

No need for another full LLVM installation if Zig is already installed.
By compiling the example code using `zig` instead of installing `wasi-sdk`.

Doc: C code can also be compiled using Zig

---

docker/docker-compose-ubuntu-1804-intel-sgx.yml

This patch simply adds the missing container name of teaclave-file-service in DCAP docker compose file.
Fixes #557

Fix container name of teaclave-file-service missing

---

.github/workflows/ci.yml

Pining openssl to version 1.1 in CI for macos.
Tested by the GitHub Action CI.

Pin openssl to version 1.1

---

executor/src/wamr.rs

Function `wasm_runtime_init ` may fail. This PR validates the return value.

[WAMR] check init return values

---

examples/python/wasm_rust_psi_payload/Cargo.lock
rpc/src/request.rs
sdk/python/teaclave.py
services/proto/proto_gen/templates/proto.j2
tests/scripts/functional_tests.py
types/src/staged_function.rs

This PR optimize memory footprint of RPC (i.e., memory used by serde).
Serde uses up more than 10x memory to deserialize a json message when using `#[serde(flatten)]` and `#[serde(tag = "request"]`.
In our case, we cannot handle more than 2M message because serde will allocation more than 100M bytes memory. The root cause is still unknown. With this PR, we can safely handle large requests in our services.
Note that this PR does not fix the Swift SDK accordingly. I'll fix it in later PRs.
CI tests.

Optimize memory footprint of serde in RPC

---

services/storage/enclave/src/lib.rs
services/storage/enclave/src/service.rs

Change the mockdb to use persistent storage in test mode.

[Mod] Persistent MockDB in test mode.

---

common/rusty_leveldb_sgx/src/cache.rs
services/storage/enclave/src/service.rs

In persistent mode, a LevelDB LRU assertion failure is triggered by our unit test case. This PR fix the issue in LRU::remove opertion.

[Fix] leveldb lru bug, using disk db for unit test.

---

docker/run-teaclave-services.sh

Add the `-b` option to `docker/run-teaclave-services.sh` so that user can choose to rebuild all services, i.e., using `--build` argument to `docker-compose`.
Local testing.

Add the -b argument to rebuild services

---

CMakeLists.txt

In a clean clone, you cannot build with `make -j4` because of some target dependency issue. This PR fixes target depends to avoid issues in parallel make.
CI tests.

Fix target depends to avoid issues in parallel make

---

cmake/scripts/gen_cov.sh
docker/build.ubuntu-1804.sgx-2.14.Dockerfile
docker/build.ubuntu-1804.sgx-dcap-1.11.Dockerfile
docker/build.ubuntu-2004.sgx-2.15.1.Dockerfile
docker/build.ubuntu-2004.sgx-dcap-1.12.1.Dockerfile
examples/python/wasm_tvm_mnist_payload/Makefile

Code coverage report generation has been stopped for a while due to toolchain upgrade. This PR fixes the report generation command `cmake -DCOV=ON` and `make cov`
Please release a set of build image after the merge.
Code coverage report has been generated successfully at https://gist.github.com/dingelish/186ecb02002bb273a47e0cbfd1196483

fix: code coverage report generation

---

sdk/python/teaclave.py

`ResetUserPasswordResponse`  is defined as
```Protobuf
message ResetUserPasswordResponse {
string password = 1;
}
```
https://github.com/apache/incubator-teaclave/blob/55e658d96b92389cb8bd203640432c9493711dd3/services/proto/src/proto/teaclave_authentication_service.proto#L81
Therefore, the response is `password`.

Fix python sdk

---

cmake/scripts/test.sh
examples/c/builtin_ordered_set_intersect.c
examples/python/mesapy_optional_files.py
examples/python/mesapy_optional_files_payload.py
examples/rust/builtin_ordered_set_intersect/src/main.rs
sdk/python/teaclave.py
services/management/enclave/src/service.rs
services/proto/src/proto/teaclave_frontend_service.proto
services/proto/src/teaclave_frontend_service.rs
tests/functional/enclave/src/end_to_end/builtin_gbdt_train.rs
tests/functional/enclave/src/end_to_end/mesapy_data_fusion.rs
tests/functional/enclave/src/management_service.rs
types/src/function.rs
types/src/task_state.rs

This PR introduces optional input/output files.
For some tasks in biometric computing, the number of input/output files varies case by case. Therefore, this PR adds a new feature called optional files. Once a file is marked with `option: True`, users do not need to register the files before creating tasks. The C, Python, Rust SDKs have been updated accordingly.

Support optional input/output files

---

examples/python/wasm_rust_psi_payload/Makefile

Ignore rustflags set by the build system when compiling wasm payload.
https://ci.mesalock-linux.org/mssun/incubator-teaclave/139

Ignore rustflags set by the build system when compiling wasm payload

---

docker/run-teaclave-services.sh

Fix the `run-teaclave-services.sh` script. If files in `/dev/sgx` are symlinks, the current implementation will fail.
Run scripts lcoally.

fix(docker): fix  detect device file with symlink

---

.drone.yml
cmake/scripts/gen_cov.sh
cmake/scripts/llvm-gcov.sh
cmake/scripts/test.sh
tests/integration/enclave/Enclave.config.xml

Fix inaccuracy of the coverage report. There three main reasons:
- use llvm-cov-11 instead of the default llvm (which may be llvm 10)
- increase heap and stack for the enclave of the integration test
- exclude some unnecessary when capture the coverage info
The new coverage result has been uploaded to coveralls: https://coveralls.io/builds/46626151
https://ci.mesalock-linux.org/mssun/incubator-teaclave/151

Fix generate testing code coverage

---

.github/workflows/ci.yml
CMakeLists.txt
cmake/scripts/build_in_ci.sh
cmake/tomls/Cargo.sgx_trusted_lib.lock
cmake/tomls/Cargo.sgx_untrusted_app.lock
cmake/tomls/Cargo.unix_app.lock
docs/release-guide.md
examples/rust/builtin_echo/Cargo.lock
examples/rust/builtin_ordered_set_intersect/Cargo.lock
file_agent/Cargo.toml
file_agent/src/agent.rs
sdk/rust/Cargo.lock
services/execution/enclave/src/service.rs
services/proto/Cargo.toml
services/proto/proto_gen/Cargo.lock
services/proto/proto_gen/Cargo.toml
tools/sgx_tool/app/Cargo.toml
tools/sgx_tool/app/src/main.rs

- Update crates that have vulnerabilities.
- Compile the source code in release mode to reduce output size.
- A Doc fix.

Commits after release

---

docker/build.ubuntu-1804-sgx-2.17.1.Dockerfile
docker/build.ubuntu-1804-sgx-dcap-1.14.Dockerfile

`docker build` for `build.ubuntu-1804-sgx-2.17.1.Dockerfile` and `build.ubuntu-1804-sgx-dcap-1.14.Dockerfile` fails due to missing dependency of `tomli`, a Python library.
```
$ docker build -t ubuntu-1804-sgx-2.17.1:latest . -f  docker/build.ubuntu-1804-sgx-dcap-1.14.Dockerfile
Could not find a version that satisfies the requirement tomli>=2.0.1 (from yapf) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3)
No matching distribution found for tomli>=2.0.1 (from yapf)
The command '/bin/sh -c pip3 install pyopenssl==21.0.0 toml cryptography yapf requests Pillow' returned a non-zero code: 1
```
I confirmed this issue doesn't happen with `build.ubuntu-2004-sgx-2.17.1.Dockerfile` or …

Fix docker build issue caused by missing dependency of tomli

---

docs/azure-confidential-computing.md

The instruction for deployment on Azure doesn't work due to SGX 2.14 is used in the docker image `teaclave/teaclave-build-ubuntu-1804-sgx-2.14`.
Now that SGX 2.17 is required,  `teaclave/teaclave-build-ubuntu-1804-sgx-2.17.1` should be used.
Confirmed `docker run` passes with the new instruction.

Fix deploy instruction for Azure to comply with SGX 2.17.

---

docker/runtime.config.toml

The runtime configuration for docker-compose has missing schemas in advertised addresses for services which will trigger an error if one tries to run Teaclave via docker-compose.
Fixes #706

Fix advertised address
